{*
** Header for Lisp-style List Library
** Include this when using EXTERNAL list
*}

{* ============== Constants ============== *}

CONST LNil = 0

' Type tags
CONST LTypeNil = 0
CONST LTypeInt = 1
CONST LTypeLng = 2
CONST LTypeSng = 3
CONST LTypeStr = 4
CONST LTypeList = 5

{* ============== Initialization ============== *}

DECLARE SUB LInit EXTERNAL
DECLARE SUB LCleanup EXTERNAL

{* ============== Cell Creation - Prepend (O(1)) ============== *}

DECLARE SUB ADDRESS LCons%(SHORTINT v, ADDRESS tail) EXTERNAL
DECLARE SUB ADDRESS LCons&(LONGINT v, ADDRESS tail) EXTERNAL
DECLARE SUB ADDRESS LCons!(SINGLE v, ADDRESS tail) EXTERNAL
DECLARE SUB ADDRESS LCons$(src$, ADDRESS tail) EXTERNAL
DECLARE SUB ADDRESS LConsList(ADDRESS ptr, ADDRESS tail) EXTERNAL

{* ============== Cell Creation - Append (O(n)) ============== *}

DECLARE SUB ADDRESS LSnoc%(SHORTINT v, ADDRESS lst) EXTERNAL
DECLARE SUB ADDRESS LSnoc&(LONGINT v, ADDRESS lst) EXTERNAL
DECLARE SUB ADDRESS LSnoc!(SINGLE v, ADDRESS lst) EXTERNAL
DECLARE SUB ADDRESS LSnoc$(src$, ADDRESS lst) EXTERNAL
DECLARE SUB ADDRESS LSnocList(ADDRESS ptr, ADDRESS lst) EXTERNAL

{* ============== Accessors ============== *}

DECLARE SUB SHORTINT LCar%(ADDRESS lst) EXTERNAL
DECLARE SUB LONGINT LCar&(ADDRESS lst) EXTERNAL
DECLARE SUB SINGLE LCar!(ADDRESS lst) EXTERNAL
DECLARE SUB STRING LCar$(ADDRESS lst) EXTERNAL
DECLARE SUB ADDRESS LCar(ADDRESS lst) EXTERNAL

DECLARE SUB ADDRESS LCdr(ADDRESS lst) EXTERNAL
DECLARE SUB ADDRESS LRest(ADDRESS lst) EXTERNAL

{* ============== Convenience Accessors ============== *}

DECLARE SUB SHORTINT LFirst%(ADDRESS lst) EXTERNAL
DECLARE SUB LONGINT LFirst&(ADDRESS lst) EXTERNAL
DECLARE SUB SINGLE LFirst!(ADDRESS lst) EXTERNAL
DECLARE SUB STRING LFirst$(ADDRESS lst) EXTERNAL
DECLARE SUB ADDRESS LFirst(ADDRESS lst) EXTERNAL

DECLARE SUB SHORTINT LSecond%(ADDRESS lst) EXTERNAL
DECLARE SUB LONGINT LSecond&(ADDRESS lst) EXTERNAL
DECLARE SUB SINGLE LSecond!(ADDRESS lst) EXTERNAL
DECLARE SUB STRING LSecond$(ADDRESS lst) EXTERNAL
DECLARE SUB ADDRESS LSecond(ADDRESS lst) EXTERNAL

{* ============== Predicates & Info ============== *}

DECLARE SUB SHORTINT LNull(ADDRESS lst) EXTERNAL
DECLARE SUB SHORTINT LType(ADDRESS lst) EXTERNAL
DECLARE SUB LONGINT LLen(ADDRESS lst) EXTERNAL

{* ============== Builder Pattern ============== *}

DECLARE SUB LNew EXTERNAL
DECLARE SUB LAdd%(SHORTINT v) EXTERNAL
DECLARE SUB LAdd&(LONGINT v) EXTERNAL
DECLARE SUB LAdd!(SINGLE v) EXTERNAL
DECLARE SUB LAdd$(src$) EXTERNAL
DECLARE SUB LAddList(ADDRESS ptr) EXTERNAL
DECLARE SUB ADDRESS LEnd EXTERNAL

{* ============== List Operations - Non-destructive ============== *}

DECLARE SUB ADDRESS LAppend(ADDRESS a, ADDRESS b) EXTERNAL
DECLARE SUB ADDRESS LRev(ADDRESS lst) EXTERNAL
DECLARE SUB ADDRESS LCopy(ADDRESS lst) EXTERNAL
DECLARE SUB ADDRESS LNth(ADDRESS lst, SHORTINT n) EXTERNAL

{* ============== List Operations - Destructive ============== *}

DECLARE SUB LNconc(ADDRESS a, ADDRESS b) EXTERNAL
DECLARE SUB ADDRESS LNrev(ADDRESS lst) EXTERNAL
DECLARE SUB LFree(ADDRESS lst) EXTERNAL

{* ============== Debugging ============== *}

DECLARE SUB LDump(ADDRESS lst) EXTERNAL
DECLARE SUB LDumpLn(ADDRESS lst) EXTERNAL
