#ifndef SUBMODS_TASKUTIL_H
#define SUBMODS_TASKUTIL_H

DECLARE SUB LONGINT TaskLaunch(LONGINT taskNameAddr, LONGINT entryPoint, LONGINT pri, LONGINT stackSize, LONGINT userData) EXTERNAL
DECLARE SUB LONGINT TaskGetData EXTERNAL
DECLARE SUB TaskTerminate(LONGINT hTask) EXTERNAL

#endif
